"""Skill matching keywords used for deterministic resume parsing."""

MATCHING_KEYWORDS = {
    "Python": ["python"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "Go": ["golang", " go "],
    "SQL": ["sql", "postgres", "mysql", "postgresql", "database query"],
    "Statistics": ["statistic"],
    "Probability": ["probability"],
    "Excel": ["excel"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy", "np."],
    "Machine Learning": ["machine learning", " ml ", "scikit"],
    "Deep Learning": ["deep learning", "neural network", "tensorflow", "pytorch"],
    "PyTorch": ["pytorch"],
    "TensorFlow": ["tensorflow", "keras"],
    "Scikit-learn": ["scikit-learn", "scikit learn", "sklearn"],
    "Data Visualization": ["visualization", "visualisation", "matplotlib", "seaborn", "plotly"],
    "Power BI": ["power bi", "powerbi"],
    "Tableau": ["tableau"],
    "Matplotlib": ["matplotlib"],
    "Docker": ["docker", "container"],
    "Kubernetes": ["kubernetes", "k8s"],
    "AWS": ["aws", "amazon web services", "lambda", "s3", "ec2"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud"],
    "CI/CD": ["ci/cd", "jenkins", "github actions", "pipeline"],
    "Git": ["git", "github", "gitlab", "version control"],
    "React": ["react", "react.js", "reactjs"],
    "Vue.js": ["vue"],
    "HTML/CSS": ["html", "css", "front-end", "frontend"],
    "REST APIs": ["rest api", "restful", "api development"],
    "GraphQL": ["graphql"],
    "Node.js": ["node.js", "nodejs", "node"],
    "FastAPI": ["fastapi"],
    "Django": ["django"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MongoDB": ["mongodb", "mongo"],
    "Redis": ["redis"],
    "Communication": ["communication", "presentation", "presented"],
    "Problem Solving": ["problem solving", "troubleshooting", "analytical"],
    "Leadership": ["leadership", "lead", "team lead", "managed"],
    "Networking": ["networking", "tcp/ip", "network security", "cisco"],
    "Linux": ["linux", "unix", "bash", "shell"],
    "APIs": ["apis", "api"],
    "Security Tools": ["wireshark", "nmap", "burp", "metasploit", "splunk", "siem"],
    "Docker": ["docker", "containerization"],
}
